<?php
/* THIS PLUGIN WAS GENERATED USING AI
/*
Plugin Name: Manage Reusable Patterns
Description: This plugin does what WP Devs overlooked: It adds a submenu that lets you easily access the Manage Reusable Patterns page of the Gutenberg editor. Find it in the Appearance menu. This plugin was created for 6.4 Alpha and above.
Version: 0.01
Author: WIKKO & Madame A.I.
*/

// Function to add the menu item/sub menu item - you can adjust this here. Replace '_submenu_' with '_menu_' to have the item appear at the top level of the navigation. Only on the top level the icon can be replaced.
function add_custom_submenu_item() {
    add_submenu_page(
        'themes.php', // Parent menu (slug of the "Posts" menu)
        'Edit your patterns here', // Page title
        'Manage Patterns', // Menu title
        'manage_options', // Capability required to access the menu item
        'edit.php?post_type=wp_block', // Link to wp_block subpage to edit the block patterns generated by Gutenberg editor
        '', // Callback function could be inserted here
        'dashicons-layout', // icon can be replaced here
        25 // Position of the menu item in the admin menu
    );
}
add_action('admin_menu', 'add_custom_submenu_item');
